### ISSUE TITLE
Unrecognized option '--preserve-input-order'

### ISSUE THREAD

**Issue by haoliangyu** [mapbox/tippecanoe#277]
I try to use the option `--preserve-input-order` but it is unrecognized. Here is the full error message:

```
Unhandled rejection Error: Command failed: cat ./tile-generator/temp/statistic.geojson | tippecanoe --output=./tile-server/tiles/statistic.mbtiles --layer=florence_statistic --maximum-zoom=10 --minimum-zoom=3 --force --drop-polygons --no-polygon-splitting --preserve-input-order
tippecanoe: unrecognized option '--preserve-input-order'
Usage: tippecanoe --output=output.mbtiles [--name=...] [--layer=...]
         [--attribution=...] [--named-layer=...] [--maximum-zoom=...]
         [--minimum-zoom=...] [--base-zoom=...] [--full-detail=...]
         [--low-detail=...] [--minimum-detail=...] [--exclude=...]
         [--include=...] [--drop-rate=...] [--buffer=...]
         [--temporary-directory=...] [--gamma=...] [--prevent=...]
         [--additional=...] [--projection=...] [--simplification=...]
         [--exclude-all] [--force] [--allow-existing] [--quiet]
         [--version] [--read-parallel] [--coalesce] [--reverse]
         [--reorder] [--drop-lines] [--check-polygons]
         [--drop-polygons] [--prefer-radix-sort]
         [--calculate-feature-density] [--no-line-simplification]
         [--simplify-only-low-zooms] [--no-feature-limit]
         [--no-tile-size-limit] [--force-feature-limit]
         [--preseve-input-order] [--no-polygon-splitting]
         [--no-clipping] [--no-duplication] [file.json ...]

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)

```

**UPDATE**:

It seems to be a typo. See `--preseve-input-order` in the error message.

**Comment by ericfischer** [comment]
Thanks! It'll be fixed in https://github.com/mapbox/tippecanoe/pull/279
