### ISSUE TITLE
Sometimes the generated mbtiles files are corrupt

### ISSUE THREAD

**Issue by JamesChevalier** [mapbox/tippecanoe#855]
Here's an example file that doesn't work properly:
[bad.mbtiles.zip](https://github.com/mapbox/tippecanoe/files/4546661/bad.mbtiles.zip)

I'm generating the file with:

```
tippecanoe -o file.mbtiles -z12 --extend-zooms-if-still-dropping file.geojson --force --quiet --read-parallel
```

The GeoJSON is generated dynamically. It's difficult for me to get a copy of that, because I don't know that the mbtiles file is corrupt until after the GeoJSON has been removed. If that data is critical to this issue, I'll have to figure something out. 🤔 

In Mapbox GL JS, it only renders some of the tiles at some of the zoom levels.
In mbview, it produces an error:

```
ReferenceError: /Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/views/raster.ejs:33
    31|   var map = L.mapbox.map('map').setView([center[1], center[0]], center[2]);
    32|   var baselayer = L.tileLayer('http://b.tiles.mapbox.com/v4/mapbox.<%= basemap %>/{z}/{x}/{y}.png?access_token=<%= accessToken %>').addTo(map);
 >> 33|   var tilelayer = L.tileLayer('http://localhost:<%= port %>/' + source + '/{z}/{x}/{y}.<%= format %>', { maxNativeZoom: <%= maxzoom %> }).addTo(map);
    34|   var hash = L.hash(map);
    35| </script>
    36| </body>

format is not defined
    at eval (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/views/raster.ejs:28:26)
    at raster (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/node_modules/express/lib/response.js:1012:7)
    at /Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/mbview.js:64:13
    at Layer.handle [as handle_request] (/Users/jim/.nodenv/versions/10.20.0/lib/node_modules/mbview/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by ericfischer** [comment]
The thing that stands out about this `mbtiles` file is that it has no `metadata` table, which is why `mbview` doesn't work. I can only guess that Tippecanoe crashed when it was part of the way through creating the file, because the `metadata` is always the last thing to be added, after tiling is complete. Do you have any error output from the failing runs?

**Comment by JamesChevalier** [comment]
I don't have error output, unfortunately. This code runs in short-lived docker containers that I treat with great disrespect. 😆 

I've also not seen this happen again after modifying the command slightly by adding `--drop-densest-as-needed`:
```
tippecanoe -o file.mbtiles -z12 --drop-densest-as-needed --extend-zooms-if-still-dropping file.geojson --force --quiet --read-parallel
```

I'm fine with this issue being closed with the reason being "Tippecanoe probably crashed", since it's so old & I haven't received any complaints about broken maps in quite some time.

Thanks for the tip about looking into crashes if the `metadata` table is empty!
