### ISSUE TITLE
Corrupted pmtiles generated - floating point exception

### ISSUE THREAD

**Issue by Mtehabsim** [mapbox/tippecanoe#991]
convert geojson to pmtiles:
tippecanoe -o california.pmtiles -l cali california.geojson --force
1 features, 7510 bytes of geometry and attributes, 205 bytes of string pool, 0 bytes of vertices, 0 bytes of nodes
zsh: floating point exception  tippecanoe -o california.pmtiles -l cali california.geojson --force
convert geojson to pmtiles:
tippecanoe -o california.pmtiles -l cali california.geojson --force
1 features, 7510 bytes of geometry and attributes, 205 bytes of string pool, 0 bytes of vertices, 0 bytes of nodes
zsh: floating point exception  tippecanoe -o california.pmtiles -l cali california.geojson --force

then i try to verify the generated file resulting in the following error:
pmtiles verify california.pmtiles
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x1281c02]

goroutine 1 [running]:
compress/gzip.(*Reader).Read(0x34610c0?, {0xc0000eb000?, 0x1010da5?, 0xc00080ab40?})
	compress/gzip/gunzip.go:247 +0x22
bufio.(*Reader).fill(0xc00080ab40)
	bufio/bufio.go:113 +0x103
bufio.(*Reader).ReadByte(0xc00080ab40)
	bufio/bufio.go:272 +0x27
encoding/binary.ReadUvarint({0x28e8620, 0xc00080ab40})
	encoding/binary/varint.go:136 +0x82
github.com/protomaps/go-pmtiles/pmtiles.deserializeEntries(0x4bb224d8?)
	github.com/protomaps/go-pmtiles/pmtiles/directory.go:166 +0x18c
github.com/protomaps/go-pmtiles/pmtiles.Verify.func1(0x0?, 0x0?, 0xc0007202c0)
	github.com/protomaps/go-pmtiles/pmtiles/verify.go:59 +0x17e
github.com/protomaps/go-pmtiles/pmtiles.Verify(0x215d7e0?, {0xc00063e090, 0x2e})
	github.com/protomaps/go-pmtiles/pmtiles/verify.go:78 +0x7a4
main.main()
	github.com/protomaps/go-pmtiles/main.go:203 +0x765

What might be the issue? the OS is Ventura 13.2.1
pmtiles 1.17.0 installed using brew
then i try to verify the generated file resulting in the following error:
pmtiles verify california.pmtiles
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x1281c02]

goroutine 1 [running]:
compress/gzip.(*Reader).Read(0x34610c0?, {0xc0000eb000?, 0x1010da5?, 0xc00080ab40?})
	compress/gzip/gunzip.go:247 +0x22
bufio.(*Reader).fill(0xc00080ab40)
	bufio/bufio.go:113 +0x103
bufio.(*Reader).ReadByte(0xc00080ab40)
	bufio/bufio.go:272 +0x27
encoding/binary.ReadUvarint({0x28e8620, 0xc00080ab40})
	encoding/binary/varint.go:136 +0x82
github.com/protomaps/go-pmtiles/pmtiles.deserializeEntries(0x4bb224d8?)
	github.com/protomaps/go-pmtiles/pmtiles/directory.go:166 +0x18c
github.com/protomaps/go-pmtiles/pmtiles.Verify.func1(0x0?, 0x0?, 0xc0007202c0)
	github.com/protomaps/go-pmtiles/pmtiles/verify.go:59 +0x17e
github.com/protomaps/go-pmtiles/pmtiles.Verify(0x215d7e0?, {0xc00063e090, 0x2e})
	github.com/protomaps/go-pmtiles/pmtiles/verify.go:78 +0x7a4
main.main()
	github.com/protomaps/go-pmtiles/main.go:203 +0x765

What might be the issue? the OS is Ventura 13.2.1
pmtiles 1.17.0 installed using brew

**Comment by Mtehabsim** [comment]
Version 2.45.0

**Comment by bdon** [comment]
@Mtehabsim is tippecanoe 2.45 installed through brew?

Can you please try to compile from source here and see if you can reproduce the problem?

Seems to be related to this:

```
1 features, 7510 bytes of geometry and attributes, 205 bytes of string pool, 0 bytes of vertices, 0 bytes of nodes
zsh: floating point exception
```

**Comment by akadouri** [comment]
I had the same issue and it was fixed by this PR https://github.com/felt/tippecanoe/commit/6a8f1b83d8ffd8c8d68ec08456740fd695e7cfca which was released in Version 2.48.0
